version: '3.5'
services:
  node_server:
    depends_on:
      - db
    env_file: ./env
    environment:
      PORT: 8080
      # Uncomment bellow line during development
      NODE_ENV: dev
    volumes:
      - ./node:/opt/app
    build:
      dockerfile: ./docker/node.Dockerfile
      context: ./
    ports:
      - 8082:8080
  rust_server:
    depends_on:
      - db
    env_file: ./env
    volumes:
      - ./rust:/opt/app
    environment:
      PORT: 8080
      RUST_LOG: info
    build:
      dockerfile: ./docker/rust.Dockerfile
      context: ./
    ports:
      - 8081:8080
  db: &db
    hostname: db
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  default:
    driver: bridge