version: '3.5'
services:
  node_server:
    depends_on:
      - node_db
    networks:
      - node_net
    env_file: ./env
    environment:
      PORT: 8080
      # Uncomment bellow line during development
      NODE_ENV: dev
    volumes:
      - ./node:/opt/app
    build:
      dockerfile: ./docker/node.Dockerfile
      context: ./
    ports:
      - 8082:8080
  rust_server:
    depends_on:
      - rust_db
    networks:
      - rust_net
    env_file: ./env
    environment:
      PORT: 8080
    build:
      dockerfile: ./docker/rust.Dockerfile
      context: ./
    ports:
      - 8081:8080
  rust_db: &db
    hostname: db
    networks:
      - rust_net
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  node_db:
    <<: *db
    networks:
      - node_net


networks:
  rust_net:
    driver: bridge
    name: rust_net
  node_net:
    driver: bridge
    name: node_net